/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ECharts: typeof import('./src/components/ECharts/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElColorPicker: (typeof import("element-plus/es"))["ElColorPicker"]
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElProgress: (typeof import("element-plus/es"))["ElProgress"]
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelectV2: (typeof import("element-plus/es"))["ElSelectV2"]
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: (typeof import("element-plus/es"))["ElSwitch"]
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: (typeof import("element-plus/es"))["ElUpload"]
    RootRootHeader: typeof import('./src/components/Root/RootHeader.vue')['default']
    RootRootNav: typeof import('./src/components/Root/RootNav.vue')['default']
    RootRootNavList: typeof import('./src/components/Root/RootNavList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StartPage: typeof import('./src/components/startPage.vue')['default']
    ToolTest: typeof import('./src/components/toolTest/index.vue')['default']
    ToolTestFour: typeof import('./src/components/toolTest/four.vue')['default']
    ToolTestOne: typeof import('./src/components/toolTest/one.vue')['default']
    ToolTestThree: typeof import('./src/components/toolTest/three.vue')['default']
    ToolTestTwo: typeof import('./src/components/toolTest/two.vue')['default']
    Upload: typeof import('./src/components/Upload.vue')['default']
    WindowTest: typeof import('./src/components/windowTest.vue')['default']
  }
}
