/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Four: typeof import('./src/components/toolTest/four.vue')['default']
    One: typeof import('./src/components/toolTest/one.vue')['default']
    RootHeader: typeof import('./src/components/Root/RootHeader.vue')['default']
    RootNav: typeof import('./src/components/Root/RootNav.vue')['default']
    RootNavList: typeof import('./src/components/Root/RootNavList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StartPage: typeof import('./src/components/startPage.vue')['default']
    Three: typeof import('./src/components/toolTest/three.vue')['default']
    ToolTest: typeof import('./src/components/toolTest/index.vue')['default']
    Two: typeof import('./src/components/toolTest/two.vue')['default']
  }
}
