/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Four: typeof import('./src/components/toolTest/four.vue')['default']
    IEpCaretLeft: typeof import('~icons/ep/caret-left')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    One: typeof import('./src/components/toolTest/one.vue')['default']
    RootHeader: typeof import('./src/components/Root/RootHeader.vue')['default']
    RootNav: typeof import('./src/components/Root/RootNav.vue')['default']
    RootNavList: typeof import('./src/components/Root/RootNavList.vue')['default']
    RootRootHeader: typeof import('./src/components/Root/RootHeader.vue')['default']
    RootRootNav: typeof import('./src/components/Root/RootNav.vue')['default']
    RootRootNavList: typeof import('./src/components/Root/RootNavList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StartPage: typeof import('./src/components/startPage.vue')['default']
    Three: typeof import('./src/components/toolTest/three.vue')['default']
    ToolTest: typeof import('./src/components/toolTest/index.vue')['default']
    ToolTestFour: typeof import('./src/components/toolTest/four.vue')['default']
    ToolTestOne: typeof import('./src/components/toolTest/one.vue')['default']
    ToolTestThree: typeof import('./src/components/toolTest/three.vue')['default']
    ToolTestTwo: typeof import('./src/components/toolTest/two.vue')['default']
    Two: typeof import('./src/components/toolTest/two.vue')['default']
  }
}
